ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ demircandemir.com.ApplicationKt.module ]
    }
    environment = development
    environment = ${?KTOR_ENV}
}

database {
    host = "localhost"
    port = "5432"
    name = "stylishdatabase"
    user = "postgres"
    password = "1852"
    maxPoolSize = 3
}

jwt {
    secret = "6f23512fe6b9d813566e2caac05a862e63c5602ab0becaade08cfb3b2617d0f356797f31ca4a8d30d6f233e83a5f15036257e3b7a889ded9b30cd0f86c9707d2b2ba5d85aedeabbc6bcc5b68af357ad8334b9c84e8033b3a2b9c0c03c332c5f710c72da57b7086cfd8e23c41839fdf0ca512c9a0f4bd268d4f56a05d69ed7a657d73a08171e774c522544126cbecf32d9b89f1f621f3345a138f65d93e4a8b24fd0824d405668226189701bc6e00d255b99dd2583774fbab5919515f4426f370ff3ad64ca3db4bb9a80eb4aea5521b474d1a10a62778fbee9f13fa18f7cf8fdb263455b4b899262816ad52a4c2e4a85296914e3a0a5870afa020f366bd300a55"
    issuer = "http://localhost:8080/"
    audience = "stylish-app-users"
    realm = "StyleApp"
}

application {
    baseUrl = "http://localhost:8080"
    environment = "dev" # Değiştirilebilir: "dev", "staging", "production"
}

email {
    smtp {
        host = "smtp.gmail.com"
        port = "587"
        user = "your.email@gmail.com" # Gmail hesabınızı girin
        password = "your-app-password" # Gmail uygulama şifrenizi girin
    }
    sender = "no-reply@stylish-app.com"
}