package demircandemir.com.presentation.routes

import demircandemir.com.application.dto.CreateOrderItemRequest
import demircandemir.com.application.dto.CreateOrderRequest
import demircandemir.com.application.dto.UpdateOrderStatusRequest
import demircandemir.com.application.dto.UpdateTrackingRequest
import demircandemir.com.application.serialization.appSerializersModule
import demircandemir.com.domain.model.*
import demircandemir.com.domain.repository.OrderItemRepository
import demircandemir.com.domain.repository.OrderRepository
import demircandemir.com.domain.repository.ProductRepository
import demircandemir.com.domain.repository.UserRepository
import demircandemir.com.infrastructure.persistence.tables.OrderStatus
import demircandemir.com.infrastructure.security.JwtConfig
import io.ktor.client.request.*
import io.ktor.client.statement.*
import io.ktor.http.*
import io.ktor.serialization.kotlinx.json.*
import io.ktor.server.application.*
import io.ktor.server.auth.*
import io.ktor.server.auth.jwt.*
import io.ktor.server.config.*
import io.ktor.server.plugins.contentnegotiation.*
import io.ktor.server.routing.*
import io.ktor.server.testing.*
import io.mockk.coEvery
import io.mockk.mockk
import kotlinx.serialization.json.Json
import org.junit.jupiter.api.Test
import java.math.BigDecimal
import java.time.LocalDateTime
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class OrderRoutesTest {
    private val mockOrderRepository: OrderRepository = mockk()
    private val mockOrderItemRepository: OrderItemRepository = mockk()
    private val mockProductRepository: ProductRepository = mockk()
    private val mockUserRepository: UserRepository = mockk()

    private val json = Json {
        prettyPrint = true
        isLenient = true
        ignoreUnknownKeys = true
        serializersModule = appSerializersModule
    }

    // Test User and JWT Setup
    private val testUserId = 1
    private val testUserRole = UserRole.CUSTOMER // Default role for most tests
    private val adminUserRole = UserRole.ADMIN

    private val jwtConfig = JwtConfig(ApplicationConfig("application-test.conf"))

    private fun createTestToken(userId: Int = testUserId, role: UserRole = testUserRole): String {
        // Create a minimal User object just for token generation
        val user = User(
            id = userId,
            email = "test@test.com",
            passwordHash = "hashedPassword",
            firstName = "Test",
            lastName = "User",
            phoneNumber = null,
            role = role,
            status = AccountStatus.ACTIVE,
            registrationDate = LocalDateTime.now(),
            lastLoginDate = null,
            verificationToken = null,
            passwordResetToken = null,
            passwordResetTokenExpiry = null,
            failedLoginAttempts = 0,
            lastFailedLoginAttempt = null
        )
        return jwtConfig.generateAccessToken(user)
    }

    private val defaultTestToken = createTestToken()
    private val adminTestToken = createTestToken(role = adminUserRole)

    // Test Order Data
    private val testOrder = Order(
        id = 1,
        userId = testUserId, // Associated with the default test user ID
        addressId = 1,
        totalAmount = BigDecimal("100.00"),
        orderDate = LocalDateTime.now(),
        paymentMethod = "Credit Card",
        orderStatus = OrderStatus.Pending,
        trackingNumber = null,
        shippingFee = BigDecimal("10.00")
    )

    private val testOrderItem = OrderItem(
        id = 1,
        orderId = 1,
        productId = 1,
        quantity = 2,
        unitPrice = BigDecimal("50.00"),
        sizeId = null,
        colorId = null
    )

    private fun Application.testModule() {
        install(ContentNegotiation) {
            json(json)
        }

        install(Authentication) {
            jwt("auth-jwt") {
                verifier(jwtConfig.verifier)
                validate { credential ->
                    // Extract claims and create JWTPrincipal
                    // We trust the token generated by our own config in tests
                    JWTPrincipal(credential.payload)
                }
            }
        }

        routing {
            authenticate("auth-jwt") {
                orderRoutes(mockOrderRepository, mockOrderItemRepository, mockProductRepository, mockUserRepository)
            }
        }
    }

    // --- Helper for setting JWT header ---
    private fun HttpRequestBuilder.jwtAuth(token: String = defaultTestToken) {
        header(HttpHeaders.Authorization, "Bearer $token")
    }

    // --- Tests ---

    @Test
    fun `GET _api_orders_{id} should return order when exists and user is owner`() {
        testApplication {
            application {
                testModule()
            }

            // Order belongs to testUserId (1), token is for testUserId (1)
            coEvery { mockOrderRepository.findById(1) } returns Result.success(testOrder)
            coEvery { mockOrderItemRepository.findByOrderId(1) } returns Result.success(listOf(testOrderItem))

            val response = client.get("/api/orders/1") {
                jwtAuth() // Use default token for user 1
            }
            assertEquals(HttpStatusCode.OK, response.status)
            assertTrue(response.bodyAsText().contains("Credit Card"))
        }
    }

    @Test
    fun `GET _api_orders_{id} should return 403 when user is not owner and not admin`() {
        testApplication {
            application {
                testModule()
            }

            // Order belongs to user 1, but token is for user 2
            val differentUserToken = createTestToken(userId = 2)
            coEvery { mockOrderRepository.findById(1) } returns Result.success(testOrder) // Order still belongs to user 1

            val response = client.get("/api/orders/1") {
                jwtAuth(differentUserToken)
            }
            assertEquals(HttpStatusCode.Forbidden, response.status)
        }
    }

    @Test
    fun `GET _api_orders_{id} should return order when user is admin but not owner`() {
        testApplication {
            application {
                testModule()
            }

            // Order belongs to user 1, token is for an admin user (e.g., user 99)
            val adminToken = createTestToken(userId = 99, role = UserRole.ADMIN)
            coEvery { mockOrderRepository.findById(1) } returns Result.success(testOrder) // Order still belongs to user 1
            coEvery { mockOrderItemRepository.findByOrderId(1) } returns Result.success(listOf(testOrderItem))

            val response = client.get("/api/orders/1") {
                jwtAuth(adminToken)
            }
            assertEquals(HttpStatusCode.OK, response.status)
            assertTrue(response.bodyAsText().contains("Credit Card"))
        }
    }

    @Test
    fun `GET _api_orders_{id} should return 404 when order does not exist`() {
        testApplication {
            application {
                testModule()
            }

            coEvery { mockOrderRepository.findById(999) } returns Result.success(null)

            val response = client.get("/api/orders/999") {
                jwtAuth() // Default user token
            }
            assertEquals(HttpStatusCode.NotFound, response.status)
        }
    }

    @Test
    fun `GET _api_orders_user_{userId} should return user orders when user requests own orders`() {
        testApplication {
            application {
                testModule()
            }

            // Requesting orders for user 1, token is for user 1
            coEvery { mockOrderRepository.findByUserId(testUserId) } returns Result.success(listOf(testOrder))

            val response = client.get("/api/orders/user/$testUserId") {
                jwtAuth() // Use default token for user 1
            }
            assertEquals(HttpStatusCode.OK, response.status)
            assertTrue(response.bodyAsText().contains("Credit Card"))
        }
    }

    @Test
    fun `GET _api_orders_user_{userId} should return 403 when user requests other user orders`() {
        testApplication {
            application {
                testModule()
            }

            // Requesting orders for user 2, but token is for user 1
            val otherUserId = 2
            coEvery { mockOrderRepository.findByUserId(otherUserId) } returns Result.success(emptyList()) // Mock doesn't matter, check happens before

            val response = client.get("/api/orders/user/$otherUserId") {
                jwtAuth() // Use default token for user 1
            }
            assertEquals(HttpStatusCode.Forbidden, response.status)
        }
    }

    @Test
    fun `GET _api_orders_user_{userId} should return orders when admin requests other user orders`() {
        testApplication {
            application {
                testModule()
            }

            // Requesting orders for user 1, token is for an admin
            val otherUserId = 1
            val adminToken = createTestToken(userId = 99, role = UserRole.ADMIN)
            coEvery { mockOrderRepository.findByUserId(otherUserId) } returns Result.success(listOf(testOrder))

            val response = client.get("/api/orders/user/$otherUserId") {
                jwtAuth(adminToken)
            }
            assertEquals(HttpStatusCode.OK, response.status)
            assertTrue(response.bodyAsText().contains("Credit Card"))
        }
    }

    @Test
    fun `GET _api_orders_status_{status} should return orders when user is admin`() {
        testApplication {
            application {
                testModule()
            }

            coEvery { mockOrderRepository.findByStatus(OrderStatus.Pending) } returns Result.success(listOf(testOrder))

            val requestStatus = "pending"
            val response = client.get("/api/orders/status/$requestStatus") {
                jwtAuth(adminTestToken) // Use admin token
            }
            assertEquals(HttpStatusCode.OK, response.status)
            assertTrue(response.bodyAsText().contains("Credit Card"))
        }
    }

    @Test
    fun `GET _api_orders_status_{status} should return 403 when user is not admin`() {
        testApplication {
            application {
                testModule()
            }

            coEvery { mockOrderRepository.findByStatus(OrderStatus.Pending) } returns Result.success(listOf(testOrder))

            val requestStatus = "pending"
            val response = client.get("/api/orders/status/$requestStatus") {
                jwtAuth() // Use default non-admin token
            }
            assertEquals(HttpStatusCode.Forbidden, response.status)
        }
    }

    @Test
    fun `POST _api_orders should create a new order when user creates own order`() {
        testApplication {
            application {
                testModule()
            }

            val orderRequest = CreateOrderRequest(
                userId = testUserId, // Creating order for user 1
                addressId = 1,
                paymentMethod = "Credit Card",
                items = listOf(CreateOrderItemRequest(productId = 1, quantity = 2)),
                shippingFee = "10.00"
            )

            coEvery { mockUserRepository.getUserById(testUserId) } returns mockk(relaxed = true)
            coEvery { mockUserRepository.getAddressById(1) } returns mockk(relaxed = true)
            coEvery { mockProductRepository.getProductById(1) } returns mockk { coEvery { price } returns BigDecimal("50.00") }
            coEvery { mockOrderRepository.create(any()) } returns Result.success(testOrder) // Assume creation returns our testOrder
            coEvery { mockOrderItemRepository.createMany(any()) } returns Result.success(listOf(testOrderItem))

            val response = client.post("/api/orders") {
                contentType(ContentType.Application.Json)
                jwtAuth() // Use default token for user 1
                setBody(Json.encodeToString(orderRequest))
            }

            assertEquals(HttpStatusCode.Created, response.status)
            assertTrue(response.bodyAsText().contains("Credit Card"))
        }
    }

    @Test
    fun `POST _api_orders should return 403 when user tries to create order for another user`() {
        testApplication {
            application {
                testModule()
            }

            val orderRequest = CreateOrderRequest(
                userId = 2, // Attempting to create order for user 2
                addressId = 1,
                paymentMethod = "Credit Card",
                items = listOf(CreateOrderItemRequest(productId = 1, quantity = 2)),
                shippingFee = "10.00"
            )

            // Mocks don't matter as Forbidden check should happen first

            val response = client.post("/api/orders") {
                contentType(ContentType.Application.Json)
                jwtAuth() // Using default token for user 1
                setBody(Json.encodeToString(orderRequest))
            }

            assertEquals(HttpStatusCode.Forbidden, response.status)
        }
    }

    @Test
    fun `POST _api_orders should create order when admin creates for another user`() {
        testApplication {
            application {
                testModule()
            }

            val targetUserId = 5
            val orderRequest = CreateOrderRequest(
                userId = targetUserId, // Admin creating order for user 5
                addressId = 1,
                paymentMethod = "Credit Card",
                items = listOf(CreateOrderItemRequest(productId = 1, quantity = 2)),
                shippingFee = "10.00"
            )

            coEvery { mockUserRepository.getUserById(targetUserId) } returns mockk(relaxed = true)
            coEvery { mockUserRepository.getAddressById(1) } returns mockk(relaxed = true)
            coEvery { mockProductRepository.getProductById(1) } returns mockk { coEvery { price } returns BigDecimal("50.00") }
            // Adjust mock order to reflect the correct userId
            val createdOrderForUser5 = testOrder.copy(userId = targetUserId)
            coEvery { mockOrderRepository.create(any()) } returns Result.success(createdOrderForUser5)
            coEvery { mockOrderItemRepository.createMany(any()) } returns Result.success(listOf(testOrderItem))

            val response = client.post("/api/orders") {
                contentType(ContentType.Application.Json)
                jwtAuth(adminTestToken) // Use admin token
                setBody(Json.encodeToString(orderRequest))
            }

            assertEquals(HttpStatusCode.Created, response.status)
            assertTrue(response.bodyAsText().contains("Credit Card"))
        }
    }


    @Test
    fun `PUT _api_orders_{id}_status should update order status when user is admin`() {
        testApplication {
            application {
                testModule()
            }
            val request = UpdateOrderStatusRequest(OrderStatus.Shipped)
            coEvery { mockOrderRepository.updateStatus(1, OrderStatus.Shipped) } returns Result.success(true)
            coEvery { mockOrderRepository.findById(1) } returns Result.success(testOrder.copy(orderStatus = OrderStatus.Shipped))
            coEvery { mockOrderItemRepository.findByOrderId(1) } returns Result.success(listOf(testOrderItem))

            val response = client.put("/api/orders/1/status") {
                contentType(ContentType.Application.Json)
                jwtAuth(adminTestToken) // Use admin token
                setBody(Json.encodeToString(request))
            }
            assertEquals(HttpStatusCode.OK, response.status)
            assertTrue(response.bodyAsText().contains("Shipped"))
        }
    }

    @Test
    fun `PUT _api_orders_{id}_status should return 403 when user is not admin`() {
        testApplication {
            application {
                testModule()
            }
            val request = UpdateOrderStatusRequest(OrderStatus.Shipped)
            // Mocks might not be needed if Forbidden check happens first
            coEvery { mockOrderRepository.updateStatus(1, OrderStatus.Shipped) } returns Result.success(true)

            val response = client.put("/api/orders/1/status") {
                contentType(ContentType.Application.Json)
                jwtAuth() // Use default non-admin token
                setBody(Json.encodeToString(request))
            }
            assertEquals(HttpStatusCode.Forbidden, response.status)
        }
    }


    @Test
    fun `PUT _api_orders_{id}_tracking should update tracking number when user is admin`() {
        testApplication {
            application {
                testModule()
            }
            val request = UpdateTrackingRequest("TRACK123", "DHL")
            coEvery { mockOrderRepository.findById(1) } returns Result.success(
                testOrder.copy(
                    trackingNumber = "TRACK123",
                    shippingProvider = "DHL"
                )
            )
            coEvery { mockOrderRepository.updateTracking(1, "TRACK123", "DHL") } returns Result.success(true)
            coEvery { mockOrderItemRepository.findByOrderId(1) } returns Result.success(listOf(testOrderItem))

            val response = client.put("/api/orders/1/tracking") {
                contentType(ContentType.Application.Json)
                jwtAuth(adminTestToken) // Use admin token
                setBody(Json.encodeToString(request))
            }
            assertEquals(HttpStatusCode.OK, response.status)
            assertTrue(response.bodyAsText().contains("TRACK123"))
        }
    }

    @Test
    fun `PUT _api_orders_{id}_tracking should return 403 when user is not admin`() {
        testApplication {
            application {
                testModule()
            }
            val request = UpdateTrackingRequest("TRACK123", "DHL")
            // Mocks might not be needed if Forbidden check happens first
            coEvery { mockOrderRepository.findById(1) } returns Result.success(testOrder)

            val response = client.put("/api/orders/1/tracking") {
                contentType(ContentType.Application.Json)
                jwtAuth() // Use default non-admin token
                setBody(Json.encodeToString(request))
            }
            assertEquals(HttpStatusCode.Forbidden, response.status)
        }
    }

    @Test
    fun `DELETE _api_orders_{id} should delete an order when user is admin`() {
        testApplication {
            application {
                testModule()
            }
            coEvery { mockOrderRepository.findById(1) } returns Result.success(testOrder)
            coEvery { mockOrderItemRepository.deleteByOrderId(1) } returns Result.success(1)
            coEvery { mockOrderRepository.delete(1) } returns Result.success(true)

            val response = client.delete("/api/orders/1") {
                jwtAuth(adminTestToken) // Use admin token
            }
            assertEquals(HttpStatusCode.NoContent, response.status)
        }
    }

    @Test
    fun `DELETE _api_orders_{id} should return 403 when user is not admin`() {
        testApplication {
            application {
                testModule()
            }
            // Mocks might not be needed if Forbidden check happens first
            coEvery { mockOrderItemRepository.deleteByOrderId(1) } returns Result.success(1)
            coEvery { mockOrderRepository.delete(1) } returns Result.success(true)

            val response = client.delete("/api/orders/1") {
                jwtAuth() // Use default non-admin token
            }
            assertEquals(HttpStatusCode.Forbidden, response.status)
        }
    }

    // --- Validation Tests (Should still work with JWT) ---

    @Test
    fun `POST _api_orders should validate product exists`() {
        testApplication {
            application {
                testModule()
            }

            val orderRequest = CreateOrderRequest(
                userId = testUserId,
                addressId = 1,
                paymentMethod = "Credit Card",
                items = listOf(CreateOrderItemRequest(productId = 999, quantity = 2)), // Non-existent product
                shippingFee = "10.00"
            )

            coEvery { mockUserRepository.getUserById(testUserId) } returns mockk(relaxed = true)
            coEvery { mockUserRepository.getAddressById(1) } returns mockk(relaxed = true)
            coEvery { mockProductRepository.getProductById(999) } returns null // Product does not exist

            val response = client.post("/api/orders") {
                contentType(ContentType.Application.Json)
                jwtAuth() // Default user token
                setBody(Json.encodeToString(orderRequest))
            }

            assertEquals(HttpStatusCode.BadRequest, response.status)
            assertTrue(response.bodyAsText().contains("Product not found"))
        }
    }

    @Test
    fun `POST _api_orders should validate user exists`() {
        testApplication {
            application {
                testModule()
            }

            val orderRequest = CreateOrderRequest(
                userId = 999, // Non-existent user
                addressId = 1,
                paymentMethod = "Credit Card",
                items = listOf(CreateOrderItemRequest(productId = 1, quantity = 2)),
                shippingFee = "10.00"
            )

            coEvery { mockUserRepository.getUserById(999) } returns null // User does not exist

            val response = client.post("/api/orders") {
                contentType(ContentType.Application.Json)
                jwtAuth(adminTestToken) // Use admin token as we are trying to create for another user
                setBody(Json.encodeToString(orderRequest))
            }

            assertEquals(HttpStatusCode.BadRequest, response.status)
            assertTrue(response.bodyAsText().contains("User not found"))
        }
    }
} 